spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to Micro_Library loans microservices related QA APIs"
  contactDetails:
    name: "Roman Svyshch - Tester"
    email: "svychroman@gmail.com"
  onCallSupport:
    - (099) 668-1573