spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to Micro_Library loans microservices api"
  contactDetails:
    name: "Roman Svyshch - Product Owner"
    email: "svychroman@gmail.com"
  onCallSupport:
    - (099) 668-1573